name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}    
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Check SSH variable
        run: |
          if [ -z "$TF_VAR_ssh_public_key" ]; then
            echo "SSH public key secret is NOT set"
            exit 1
          else
            echo "SSH public key secret is set"
          fi


      - name: Terraform Plan
        run: terraform plan -no-color